Feature/phenx parser
helxplatform/dug pull request #159
Opened 2021-06-22 12:08 UTC by YaphetKG

* Parses Phenx protocol xlsx file
* introduces linked_elements array in DugElement data class, to maintain linkage between items in same row. (this will be used by roger to extract and build KG)
* Parses Ontolgical terms in spread sheet as Dug COncepts and attaches them to LOINC , PHENX and CDE elements in that same row. The ontological terms are also normalized.
* Tests these features.

2021-06-22 13:23 UTC, cschreep requested changes
Some of the code in the body of for-loops or conditionals can be extracted into testable functions

2021-06-22 13:23 UTC, cschreep commented on src/dug/core/parsers/phenx_protocol_parser.py
> +        for row in PhenXParser.get_parsed_row(input_file):
Everything in the body of this for-loop should be moved to a separate function

2021-06-22 13:23 UTC, cschreep commented on src/dug/core/parsers/phenx_protocol_parser.py
> +        http_session = factory.build_http_session()
The declaration of this element is far removed from its use

2022-08-17 14:01 UTC, closed without merging

2022-08-17 14:02 UTC, YaphetKG commented
Instead of parsing Phenx csv here, we will adopt the way the pattern of parsing it to a common format that would be used by one of the dug parsers